/**
 * MeteoraDammV2.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` pool_authority (readonly)
 * `[2]` pool (writable)
 * `[3]` input_token_account (writable)
 * `[4]` output_token_account (writable)
 * `[5]` token_a_vault (writable)
 * `[6]` token_b_vault (writable)
 * `[7]` token_a_mint (readonly)
 * `[8]` token_b_mint (readonly)
 * `[9]` payer (signer)
 * `[10]` token_a_program (readonly)
 * `[11]` token_b_program (readonly)
 * `[12]` referral_token_account (writable)
 * `[13]` event_authority (readonly)
 * `[14]` program_self (readonly)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { INSTRUCTIONS_SYSVAR_ADDRESS } from "../programs.js";
import {
  VenueWindow,
  readonlyAccount,
  readonlySignerAccount,
  writableAccount,
  writableOrSentinel,
} from "./window.js";

/** `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG` */
export const PROGRAM_ADDRESS: Address = address("cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG");

/** `HLnpSz9h2S4hiLQ43rnSD9XkcUThA7B8hQMKmDaiTLcC` */
export const POOL_AUTHORITY: Address = address("HLnpSz9h2S4hiLQ43rnSD9XkcUThA7B8hQMKmDaiTLcC");

/** `3rmHSu74h1ZcmAisVcWerTCiRDQbUrBKmcwptYGjHfet` */
export const EVENT_AUTHORITY: Address = address("3rmHSu74h1ZcmAisVcWerTCiRDQbUrBKmcwptYGjHfet");

/** Which window form this hop sends. */
export const DammV2Form = {
  Base: "Base",
  RateLimited: "RateLimited",
} as const;

export type DammV2Form = (typeof DammV2Form)[keyof typeof DammV2Form];

export interface MeteoraDammV2Accounts {
  readonly pool: Address;
  /** The token account this hop spends from. */
  readonly inputTokenAccount: Address;
  /** The token account this hop receives into. */
  readonly outputTokenAccount: Address;
  readonly tokenAVault: Address;
  readonly tokenBVault: Address;
  readonly tokenAMint: Address;
  readonly tokenBMint: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly payer: Address;
  readonly tokenAProgram: Address;
  readonly tokenBProgram: Address;
  /** Unset sends the venue's own program address, which it reads as no value. */
  readonly referralTokenAccount: Address | undefined;
}

export function resolve(accounts: MeteoraDammV2Accounts, form: DammV2Form): VenueWindow {
  return new VenueWindow(HopKind.MeteoraDammV2, [
    readonlyAccount(PROGRAM_ADDRESS),
    readonlyAccount(POOL_AUTHORITY),
    writableAccount(accounts.pool),
    writableAccount(accounts.inputTokenAccount),
    writableAccount(accounts.outputTokenAccount),
    writableAccount(accounts.tokenAVault),
    writableAccount(accounts.tokenBVault),
    readonlyAccount(accounts.tokenAMint),
    readonlyAccount(accounts.tokenBMint),
    readonlySignerAccount(accounts.payer),
    readonlyAccount(accounts.tokenAProgram),
    readonlyAccount(accounts.tokenBProgram),
    writableOrSentinel(accounts.referralTokenAccount, PROGRAM_ADDRESS),
    readonlyAccount(EVENT_AUTHORITY),
    readonlyAccount(PROGRAM_ADDRESS),
    ...(form === DammV2Form.RateLimited ? [readonlyAccount(INSTRUCTIONS_SYSVAR_ADDRESS)] : []),
  ]);
}
