/**
 * MeteoraDlmmSwap.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` lb_pair (writable)
 * `[2]` bin_array_bitmap_extension (writable)
 * `[3]` reserve_x (writable)
 * `[4]` reserve_y (writable)
 * `[5]` user_token_in (writable)
 * `[6]` user_token_out (writable)
 * `[7]` mint_x (readonly)
 * `[8]` mint_y (readonly)
 * `[9]` oracle (writable)
 * `[10]` host_fee_in (writable)
 * `[11]` user (signer)
 * `[12]` token_x_program (readonly)
 * `[13]` token_y_program (readonly)
 * `[14]` event_authority (readonly)
 * `[15]` program_self (readonly)
 * `[16]` bin_array (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { TOKEN_PROGRAM_ADDRESS } from "../programs.js";
import { assertTailLength, type TupleRange } from "./tail.js";
import {
  VenueWindow,
  readonlyAccount,
  readonlySignerAccount,
  writableAccount,
  writableOrSentinel,
} from "./window.js";

/** `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo` */
export const PROGRAM_ADDRESS: Address = address("LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo");

/** `D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6` */
export const EVENT_AUTHORITY: Address = address("D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6");

const MIN_BINS = 1;
/** The tail's longest reach. */
export const MAX_BINS = 8;
/** This venue's variable tail, bounded by its type. */
export type BinArrayTail = TupleRange<Address, typeof MIN_BINS, typeof MAX_BINS>;

export interface MeteoraDlmmSwapAccounts {
  readonly lbPair: Address;
  /** Unset sends the venue's own program address, which it reads as no value. */
  readonly binArrayBitmapExtension: Address | undefined;
  readonly reserveX: Address;
  readonly reserveY: Address;
  /** The token account this hop spends from. */
  readonly userTokenIn: Address;
  /** The token account this hop receives into. */
  readonly userTokenOut: Address;
  readonly mintX: Address;
  readonly mintY: Address;
  readonly oracle: Address;
  /** Unset sends the venue's own program address, which it reads as no value. */
  readonly hostFeeIn: Address | undefined;
  /** The signer whose token accounts the swap moves through. */
  readonly user: Address;
}

export function resolve(accounts: MeteoraDlmmSwapAccounts, tail: BinArrayTail): VenueWindow {
  assertTailLength(tail, MIN_BINS, MAX_BINS);
  return new VenueWindow(HopKind.MeteoraDlmmSwap, [
    readonlyAccount(PROGRAM_ADDRESS),
    writableAccount(accounts.lbPair),
    writableOrSentinel(accounts.binArrayBitmapExtension, PROGRAM_ADDRESS),
    writableAccount(accounts.reserveX),
    writableAccount(accounts.reserveY),
    writableAccount(accounts.userTokenIn),
    writableAccount(accounts.userTokenOut),
    readonlyAccount(accounts.mintX),
    readonlyAccount(accounts.mintY),
    writableAccount(accounts.oracle),
    writableOrSentinel(accounts.hostFeeIn, PROGRAM_ADDRESS),
    readonlySignerAccount(accounts.user),
    readonlyAccount(TOKEN_PROGRAM_ADDRESS),
    readonlyAccount(TOKEN_PROGRAM_ADDRESS),
    readonlyAccount(EVENT_AUTHORITY),
    readonlyAccount(PROGRAM_ADDRESS),
    ...tail.map(writableAccount),
  ]);
}
