/**
 * MeteoraDlmmSwap2.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` pool (writable)
 * `[2]` bin_array_bitmap_extension (writable)
 * `[3]` reserve_x (writable)
 * `[4]` reserve_y (writable)
 * `[5]` user_token_in (writable)
 * `[6]` user_token_out (writable)
 * `[7]` token_x_mint (readonly)
 * `[8]` token_y_mint (readonly)
 * `[9]` oracle (writable)
 * `[10]` host_fee_in (writable)
 * `[11]` user (signer)
 * `[12]` token_x_program (readonly)
 * `[13]` token_y_program (readonly)
 * `[14]` memo_program (readonly)
 * `[15]` event_authority (readonly)
 * `[16]` program_self (readonly)
 * `[17]` bin_array (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { MEMO_PROGRAM_ADDRESS } from "../programs.js";
import { assertTailLength, type TupleRange } from "./tail.js";
import {
  VenueWindow,
  readonlyAccount,
  readonlySignerAccount,
  writableAccount,
  writableOrSentinel,
} from "./window.js";

/** `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo` */
export const PROGRAM_ADDRESS: Address = address("LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo");

/** `D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6` */
export const EVENT_AUTHORITY: Address = address("D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6");

const MIN_BIN_ARRAYS = 1;
/** The tail's longest reach. */
export const MAX_BIN_ARRAYS = 8;
/** This venue's variable tail, bounded by its type. */
export type BinArrayTail = TupleRange<Address, typeof MIN_BIN_ARRAYS, typeof MAX_BIN_ARRAYS>;

export interface MeteoraDlmmSwap2Accounts {
  readonly pool: Address;
  /** Unset sends the venue's own program address, which it reads as no value. */
  readonly binArrayBitmapExtension: Address | undefined;
  readonly reserveX: Address;
  readonly reserveY: Address;
  /** The token account this hop spends from. */
  readonly userTokenIn: Address;
  /** The token account this hop receives into. */
  readonly userTokenOut: Address;
  readonly tokenXMint: Address;
  readonly tokenYMint: Address;
  readonly oracle: Address;
  /** Unset sends the venue's own program address, which it reads as no value. */
  readonly hostFeeIn: Address | undefined;
  /** The signer whose token accounts the swap moves through. */
  readonly user: Address;
  readonly tokenXProgram: Address;
  readonly tokenYProgram: Address;
}

export function resolve(accounts: MeteoraDlmmSwap2Accounts, tail: BinArrayTail): VenueWindow {
  assertTailLength(tail, MIN_BIN_ARRAYS, MAX_BIN_ARRAYS);
  return new VenueWindow(HopKind.MeteoraDlmmSwap2, [
    readonlyAccount(PROGRAM_ADDRESS),
    writableAccount(accounts.pool),
    writableOrSentinel(accounts.binArrayBitmapExtension, PROGRAM_ADDRESS),
    writableAccount(accounts.reserveX),
    writableAccount(accounts.reserveY),
    writableAccount(accounts.userTokenIn),
    writableAccount(accounts.userTokenOut),
    readonlyAccount(accounts.tokenXMint),
    readonlyAccount(accounts.tokenYMint),
    writableAccount(accounts.oracle),
    writableOrSentinel(accounts.hostFeeIn, PROGRAM_ADDRESS),
    readonlySignerAccount(accounts.user),
    readonlyAccount(accounts.tokenXProgram),
    readonlyAccount(accounts.tokenYProgram),
    readonlyAccount(MEMO_PROGRAM_ADDRESS),
    readonlyAccount(EVENT_AUTHORITY),
    readonlyAccount(PROGRAM_ADDRESS),
    ...tail.map(writableAccount),
  ]);
}
