/**
 * MeteoraDammV1.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` pool (writable)
 * `[2]` user_source (writable)
 * `[3]` user_dest (writable)
 * `[4]` a_vault (writable)
 * `[5]` b_vault (writable)
 * `[6]` a_token_vault (writable)
 * `[7]` b_token_vault (writable)
 * `[8]` a_vault_lp_mint (writable)
 * `[9]` b_vault_lp_mint (writable)
 * `[10]` a_vault_lp (writable)
 * `[11]` b_vault_lp (writable)
 * `[12]` protocol_token_fee (writable)
 * `[13]` payer (signer)
 * `[14]` dynamic_vault_program (readonly)
 * `[15]` token_program (readonly)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { TOKEN_PROGRAM_ADDRESS } from "../programs.js";
import { VenueWindow, readonlyAccount, readonlySignerAccount, writableAccount } from "./window.js";

/** `Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB` */
export const PROGRAM_ADDRESS: Address = address("Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB");

/** `24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi` */
export const DYNAMIC_VAULT_PROGRAM_ADDRESS: Address = address(
  "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi",
);

export interface MeteoraDammV1Accounts {
  readonly pool: Address;
  /** The token account this hop spends from. */
  readonly userSource: Address;
  /** The token account this hop receives into. */
  readonly userDest: Address;
  readonly aVault: Address;
  readonly bVault: Address;
  readonly aTokenVault: Address;
  readonly bTokenVault: Address;
  readonly aVaultLpMint: Address;
  readonly bVaultLpMint: Address;
  readonly aVaultLp: Address;
  readonly bVaultLp: Address;
  readonly protocolTokenFee: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly payer: Address;
}

export function resolve(accounts: MeteoraDammV1Accounts): VenueWindow {
  return new VenueWindow(HopKind.MeteoraDammV1, [
    readonlyAccount(PROGRAM_ADDRESS),
    writableAccount(accounts.pool),
    writableAccount(accounts.userSource),
    writableAccount(accounts.userDest),
    writableAccount(accounts.aVault),
    writableAccount(accounts.bVault),
    writableAccount(accounts.aTokenVault),
    writableAccount(accounts.bTokenVault),
    writableAccount(accounts.aVaultLpMint),
    writableAccount(accounts.bVaultLpMint),
    writableAccount(accounts.aVaultLp),
    writableAccount(accounts.bVaultLp),
    writableAccount(accounts.protocolTokenFee),
    readonlySignerAccount(accounts.payer),
    readonlyAccount(DYNAMIC_VAULT_PROGRAM_ADDRESS),
    readonlyAccount(TOKEN_PROGRAM_ADDRESS),
  ]);
}
