/**
 * PumpSwapBuy.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` pool (writable)
 * `[2]` user (writable, signer)
 * `[3]` forwarded_before_base_mint (readonly)
 * `[4]` base_mint (readonly)
 * `[5]` quote_mint (readonly)
 * `[6]` base_token_account (writable)
 * `[7]` quote_token_account (writable)
 * `[8]` base_vault (writable)
 * `[9]` quote_vault (writable)
 * `[10]` forwarded_before_volume_accumulator (readonly)
 * `[11]` forwarded_before_volume_accumulator (writable)
 * `[12]` forwarded_before_volume_accumulator (readonly)
 * `[13]` forwarded_before_volume_accumulator (readonly)
 * `[14]` forwarded_before_volume_accumulator (readonly)
 * `[15]` forwarded_before_volume_accumulator (readonly)
 * `[16]` forwarded_before_volume_accumulator (readonly)
 * `[17]` forwarded_before_volume_accumulator (readonly)
 * `[18]` forwarded_before_volume_accumulator (writable)
 * `[19]` forwarded_before_volume_accumulator (readonly)
 * `[20]` global_volume_accumulator (readonly)
 * `[21]` user_volume_accumulator (writable)
 * `[22]` fee_config (readonly)
 * `[23]` fee_program (readonly)
 * `[24]` forwarded_close (readonly)
 * `[25]` forwarded_close (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { type TupleOfLength } from "./tail.js";
import { VenueWindow, readonlyAccount, writableAccount, writableSignerAccount } from "./window.js";

/** `pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA` */
export const PROGRAM_ADDRESS: Address = address("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA");

/** `C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw` */
export const GLOBAL_VOLUME_ACCUMULATOR: Address = address(
  "C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw",
);

/** `5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx` */
export const FEE_CONFIG: Address = address("5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx");

/** `pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ` */
export const FEE_PROGRAM: Address = address("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ");

export interface PumpSwapBuyAccounts {
  readonly pool: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly user: Address;
  /** Forwarded to the venue without validation. */
  readonly forwardedBeforeBaseMint: Address;
  readonly baseMint: Address;
  readonly quoteMint: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly baseTokenAccount: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly quoteTokenAccount: Address;
  readonly baseVault: Address;
  readonly quoteVault: Address;
  /** Forwarded to the venue without validation, in order. */
  readonly forwardedBeforeVolumeAccumulator: TupleOfLength<Address, 10>;
  readonly userVolumeAccumulator: Address;
  /** Present only when the pool carries it. */
  readonly cashback: Address | undefined;
  /** Present only when the pool carries it. */
  readonly poolV2: Address | undefined;
  /** Forwarded to the venue without validation, in order. */
  readonly forwardedClose: TupleOfLength<Address, 2>;
}

export function resolve(accounts: PumpSwapBuyAccounts): VenueWindow {
  const [
    forwardedBeforeVolumeAccumulator0,
    forwardedBeforeVolumeAccumulator1,
    forwardedBeforeVolumeAccumulator2,
    forwardedBeforeVolumeAccumulator3,
    forwardedBeforeVolumeAccumulator4,
    forwardedBeforeVolumeAccumulator5,
    forwardedBeforeVolumeAccumulator6,
    forwardedBeforeVolumeAccumulator7,
    forwardedBeforeVolumeAccumulator8,
    forwardedBeforeVolumeAccumulator9,
  ] = accounts.forwardedBeforeVolumeAccumulator;
  const [forwardedClose0, forwardedClose1] = accounts.forwardedClose;
  return new VenueWindow(HopKind.PumpSwapBuy, [
    readonlyAccount(PROGRAM_ADDRESS),
    writableAccount(accounts.pool),
    writableSignerAccount(accounts.user),
    readonlyAccount(accounts.forwardedBeforeBaseMint),
    readonlyAccount(accounts.baseMint),
    readonlyAccount(accounts.quoteMint),
    writableAccount(accounts.baseTokenAccount),
    writableAccount(accounts.quoteTokenAccount),
    writableAccount(accounts.baseVault),
    writableAccount(accounts.quoteVault),
    readonlyAccount(forwardedBeforeVolumeAccumulator0),
    writableAccount(forwardedBeforeVolumeAccumulator1),
    readonlyAccount(forwardedBeforeVolumeAccumulator2),
    readonlyAccount(forwardedBeforeVolumeAccumulator3),
    readonlyAccount(forwardedBeforeVolumeAccumulator4),
    readonlyAccount(forwardedBeforeVolumeAccumulator5),
    readonlyAccount(forwardedBeforeVolumeAccumulator6),
    readonlyAccount(forwardedBeforeVolumeAccumulator7),
    writableAccount(forwardedBeforeVolumeAccumulator8),
    readonlyAccount(forwardedBeforeVolumeAccumulator9),
    readonlyAccount(GLOBAL_VOLUME_ACCUMULATOR),
    writableAccount(accounts.userVolumeAccumulator),
    readonlyAccount(FEE_CONFIG),
    readonlyAccount(FEE_PROGRAM),
    ...(accounts.cashback === undefined ? [] : [writableAccount(accounts.cashback)]),
    ...(accounts.poolV2 === undefined ? [] : [readonlyAccount(accounts.poolV2)]),
    readonlyAccount(forwardedClose0),
    writableAccount(forwardedClose1),
  ]);
}
