/**
 * PumpSwapSell.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` pool (writable)
 * `[2]` user (writable, signer)
 * `[3]` forwarded_before_base_mint (readonly)
 * `[4]` base_mint (readonly)
 * `[5]` quote_mint (readonly)
 * `[6]` base_ata (writable)
 * `[7]` quote_ata (writable)
 * `[8]` base_vault (writable)
 * `[9]` quote_vault (writable)
 * `[10]` forwarded_before_fee_config (readonly)
 * `[11]` forwarded_before_fee_config (writable)
 * `[12]` forwarded_before_fee_config (readonly)
 * `[13]` forwarded_before_fee_config (readonly)
 * `[14]` forwarded_before_fee_config (readonly)
 * `[15]` forwarded_before_fee_config (readonly)
 * `[16]` forwarded_before_fee_config (readonly)
 * `[17]` forwarded_before_fee_config (readonly)
 * `[18]` forwarded_before_fee_config (writable)
 * `[19]` forwarded_before_fee_config (readonly)
 * `[20]` fee_config (readonly)
 * `[21]` fee_program (readonly)
 * `[22]` forwarded_close (readonly)
 * `[23]` forwarded_close (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { type TupleOfLength } from "./tail.js";
import { VenueWindow, readonlyAccount, writableAccount, writableSignerAccount } from "./window.js";

/** `pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA` */
export const PROGRAM_ADDRESS: Address = address("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA");

/** `5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx` */
export const FEE_CONFIG: Address = address("5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx");

/** `pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ` */
export const FEE_PROGRAM: Address = address("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ");

export interface PumpSwapSellAccounts {
  readonly pool: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly user: Address;
  /** Forwarded to the venue without validation. */
  readonly forwardedBeforeBaseMint: Address;
  readonly baseMint: Address;
  readonly quoteMint: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly baseAta: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly quoteAta: Address;
  readonly baseVault: Address;
  readonly quoteVault: Address;
  /** Forwarded to the venue without validation, in order. */
  readonly forwardedBeforeFeeConfig: TupleOfLength<Address, 10>;
  /** Present only when the pool carries it. */
  readonly cashback: readonly [Address, Address] | undefined;
  /** Present only when the pool carries it. */
  readonly poolV2: Address | undefined;
  /** Forwarded to the venue without validation, in order. */
  readonly forwardedClose: TupleOfLength<Address, 2>;
}

export function resolve(accounts: PumpSwapSellAccounts): VenueWindow {
  const [
    forwardedBeforeFeeConfig0,
    forwardedBeforeFeeConfig1,
    forwardedBeforeFeeConfig2,
    forwardedBeforeFeeConfig3,
    forwardedBeforeFeeConfig4,
    forwardedBeforeFeeConfig5,
    forwardedBeforeFeeConfig6,
    forwardedBeforeFeeConfig7,
    forwardedBeforeFeeConfig8,
    forwardedBeforeFeeConfig9,
  ] = accounts.forwardedBeforeFeeConfig;
  const [forwardedClose0, forwardedClose1] = accounts.forwardedClose;
  return new VenueWindow(HopKind.PumpSwapSell, [
    readonlyAccount(PROGRAM_ADDRESS),
    writableAccount(accounts.pool),
    writableSignerAccount(accounts.user),
    readonlyAccount(accounts.forwardedBeforeBaseMint),
    readonlyAccount(accounts.baseMint),
    readonlyAccount(accounts.quoteMint),
    writableAccount(accounts.baseAta),
    writableAccount(accounts.quoteAta),
    writableAccount(accounts.baseVault),
    writableAccount(accounts.quoteVault),
    readonlyAccount(forwardedBeforeFeeConfig0),
    writableAccount(forwardedBeforeFeeConfig1),
    readonlyAccount(forwardedBeforeFeeConfig2),
    readonlyAccount(forwardedBeforeFeeConfig3),
    readonlyAccount(forwardedBeforeFeeConfig4),
    readonlyAccount(forwardedBeforeFeeConfig5),
    readonlyAccount(forwardedBeforeFeeConfig6),
    readonlyAccount(forwardedBeforeFeeConfig7),
    writableAccount(forwardedBeforeFeeConfig8),
    readonlyAccount(forwardedBeforeFeeConfig9),
    readonlyAccount(FEE_CONFIG),
    readonlyAccount(FEE_PROGRAM),
    ...(accounts.cashback === undefined ? [] : accounts.cashback.map(writableAccount)),
    ...(accounts.poolV2 === undefined ? [] : [readonlyAccount(accounts.poolV2)]),
    readonlyAccount(forwardedClose0),
    writableAccount(forwardedClose1),
  ]);
}
