/**
 * RaydiumClmm.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` payer (signer)
 * `[2]` amm_config (readonly)
 * `[3]` pool (writable)
 * `[4]` input_token_account (writable)
 * `[5]` output_token_account (writable)
 * `[6]` input_vault (writable)
 * `[7]` output_vault (writable)
 * `[8]` observation_state (writable)
 * `[9]` token_program (readonly)
 * `[10]` token_2022_program (readonly)
 * `[11]` memo_program (readonly)
 * `[12]` input_mint (readonly)
 * `[13]` output_mint (readonly)
 * `[14]` tick_array (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import {
  MEMO_PROGRAM_ADDRESS,
  TOKEN_2022_PROGRAM_ADDRESS,
  TOKEN_PROGRAM_ADDRESS,
} from "../programs.js";
import { assertTailLength, type TupleRange } from "./tail.js";
import { VenueWindow, readonlyAccount, readonlySignerAccount, writableAccount } from "./window.js";

/** `CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK` */
export const PROGRAM_ADDRESS: Address = address("CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK");

const TAIL_MIN = 1;
/** The tail's longest reach. */
export const TAIL_MAX = 7;
/** This venue's variable tail, bounded by its type. */
export type ClmmTail = TupleRange<Address, typeof TAIL_MIN, typeof TAIL_MAX>;

export interface RaydiumClmmAccounts {
  /** The signer whose token accounts the swap moves through. */
  readonly payer: Address;
  readonly ammConfig: Address;
  readonly pool: Address;
  /** The token account this hop spends from. */
  readonly inputTokenAccount: Address;
  /** The token account this hop receives into. */
  readonly outputTokenAccount: Address;
  readonly inputVault: Address;
  readonly outputVault: Address;
  readonly observationState: Address;
  readonly inputMint: Address;
  readonly outputMint: Address;
}

export function resolve(accounts: RaydiumClmmAccounts, tail: ClmmTail): VenueWindow {
  assertTailLength(tail, TAIL_MIN, TAIL_MAX);
  return new VenueWindow(HopKind.RaydiumClmm, [
    readonlyAccount(PROGRAM_ADDRESS),
    readonlySignerAccount(accounts.payer),
    readonlyAccount(accounts.ammConfig),
    writableAccount(accounts.pool),
    writableAccount(accounts.inputTokenAccount),
    writableAccount(accounts.outputTokenAccount),
    writableAccount(accounts.inputVault),
    writableAccount(accounts.outputVault),
    writableAccount(accounts.observationState),
    readonlyAccount(TOKEN_PROGRAM_ADDRESS),
    readonlyAccount(TOKEN_2022_PROGRAM_ADDRESS),
    readonlyAccount(MEMO_PROGRAM_ADDRESS),
    readonlyAccount(accounts.inputMint),
    readonlyAccount(accounts.outputMint),
    ...tail.map(writableAccount),
  ]);
}
