/**
 * RaydiumAmmV4.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` token_program (readonly)
 * `[2]` pool (writable)
 * `[3]` amm_authority (readonly)
 * `[4]` base_vault (writable)
 * `[5]` quote_vault (writable)
 * `[6]` user_source (writable)
 * `[7]` user_destination (writable)
 * `[8]` payer (signer)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { TOKEN_PROGRAM_ADDRESS } from "../programs.js";
import { VenueWindow, readonlyAccount, readonlySignerAccount, writableAccount } from "./window.js";

/** `675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8` */
export const PROGRAM_ADDRESS: Address = address("675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8");

/** `5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1` */
export const AMM_AUTHORITY: Address = address("5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1");

export interface RaydiumAmmV4Accounts {
  readonly pool: Address;
  readonly baseVault: Address;
  readonly quoteVault: Address;
  /** The token account this hop spends from. */
  readonly userSource: Address;
  /** The token account this hop receives into. */
  readonly userDestination: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly payer: Address;
}

export function resolve(accounts: RaydiumAmmV4Accounts): VenueWindow {
  return new VenueWindow(HopKind.RaydiumAmmV4, [
    readonlyAccount(PROGRAM_ADDRESS),
    readonlyAccount(TOKEN_PROGRAM_ADDRESS),
    writableAccount(accounts.pool),
    readonlyAccount(AMM_AUTHORITY),
    writableAccount(accounts.baseVault),
    writableAccount(accounts.quoteVault),
    writableAccount(accounts.userSource),
    writableAccount(accounts.userDestination),
    readonlySignerAccount(accounts.payer),
  ]);
}
