/**
 * Whirlpool.
 *
 * Generated by `wire-export` from the router's window schema. Do not edit: a change here
 * is a change to the deployed program's window contract, which lives there.
 *
 * `[0]` program (readonly)
 * `[1]` token_program_a (readonly)
 * `[2]` token_program_b (readonly)
 * `[3]` memo_program (readonly)
 * `[4]` token_authority (signer)
 * `[5]` whirlpool (writable)
 * `[6]` mint_a (readonly)
 * `[7]` mint_b (readonly)
 * `[8]` token_owner_account_a (writable)
 * `[9]` token_vault_a (writable)
 * `[10]` token_owner_account_b (writable)
 * `[11]` token_vault_b (writable)
 * `[12]` tick_array_0 (writable)
 * `[13]` tick_array_1 (writable)
 * `[14]` tick_array_2 (writable)
 * `[15]` oracle (writable)
 */
import { address, type Address } from "@solana/addresses";

import { HopKind } from "../hopKind.js";
import { MEMO_PROGRAM_ADDRESS } from "../programs.js";
import { assertTailLength, type TupleRange } from "./tail.js";
import { VenueWindow, readonlyAccount, readonlySignerAccount, writableAccount } from "./window.js";

/** `whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc` */
export const PROGRAM_ADDRESS: Address = address("whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");

const SUPPLEMENTAL_MIN = 0;
/** The tail's longest reach. */
export const SUPPLEMENTAL_MAX = 3;
/** This venue's variable tail, bounded by its type. */
export type SupplementalTickArrays = TupleRange<
  Address,
  typeof SUPPLEMENTAL_MIN,
  typeof SUPPLEMENTAL_MAX
>;

export interface WhirlpoolAccounts {
  readonly tokenProgramA: Address;
  readonly tokenProgramB: Address;
  /** The signer whose token accounts the swap moves through. */
  readonly tokenAuthority: Address;
  readonly whirlpool: Address;
  readonly mintA: Address;
  readonly mintB: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly tokenOwnerAccountA: Address;
  readonly tokenVaultA: Address;
  /** One of the trader's two token accounts; the leg decides which one is spent. */
  readonly tokenOwnerAccountB: Address;
  readonly tokenVaultB: Address;
  readonly tickArray0: Address;
  readonly tickArray1: Address;
  readonly tickArray2: Address;
  readonly oracle: Address;
}

export function resolve(accounts: WhirlpoolAccounts, tail: SupplementalTickArrays): VenueWindow {
  assertTailLength(tail, SUPPLEMENTAL_MIN, SUPPLEMENTAL_MAX);
  return new VenueWindow(HopKind.Whirlpool, [
    readonlyAccount(PROGRAM_ADDRESS),
    readonlyAccount(accounts.tokenProgramA),
    readonlyAccount(accounts.tokenProgramB),
    readonlyAccount(MEMO_PROGRAM_ADDRESS),
    readonlySignerAccount(accounts.tokenAuthority),
    writableAccount(accounts.whirlpool),
    readonlyAccount(accounts.mintA),
    readonlyAccount(accounts.mintB),
    writableAccount(accounts.tokenOwnerAccountA),
    writableAccount(accounts.tokenVaultA),
    writableAccount(accounts.tokenOwnerAccountB),
    writableAccount(accounts.tokenVaultB),
    writableAccount(accounts.tickArray0),
    writableAccount(accounts.tickArray1),
    writableAccount(accounts.tickArray2),
    writableAccount(accounts.oracle),
    ...tail.map(writableAccount),
  ]);
}
