//! MeteoraDammV2.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG`
//! 1. `pool_authority` — readonly, pinned `HLnpSz9h2S4hiLQ43rnSD9XkcUThA7B8hQMKmDaiTLcC`
//! 2. `pool` — writable
//! 3. `input_token_account` — writable
//! 4. `output_token_account` — writable
//! 5. `token_a_vault` — writable
//! 6. `token_b_vault` — writable
//! 7. `token_a_mint` — readonly
//! 8. `token_b_mint` — readonly
//! 9. `payer` — signer
//! 10. `token_a_program` — readonly
//! 11. `token_b_program` — readonly
//! 12. `referral_token_account` — writable
//! 13. `event_authority` — readonly, pinned `3rmHSu74h1ZcmAisVcWerTCiRDQbUrBKmcwptYGjHfet`
//! 14. `program_self` — readonly, pinned `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG`

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `3rmHSu74h1ZcmAisVcWerTCiRDQbUrBKmcwptYGjHfet`
pub const EVENT_AUTHORITY: Pubkey = Pubkey::new_from_array([
    42, 118, 231, 179, 68, 100, 10, 28, 252, 89, 76, 139, 202, 208, 160, 145, 1, 28, 172, 125, 209,
    86, 191, 131, 168, 51, 251, 34, 8, 235, 119, 173,
]);

/// `HLnpSz9h2S4hiLQ43rnSD9XkcUThA7B8hQMKmDaiTLcC`
pub const POOL_AUTHORITY: Pubkey = Pubkey::new_from_array([
    242, 204, 213, 53, 172, 165, 241, 115, 106, 200, 34, 221, 7, 115, 228, 217, 47, 189, 138, 89,
    178, 148, 3, 80, 2, 149, 169, 1, 28, 115, 169, 229,
]);

/// `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    9, 45, 33, 53, 101, 122, 21, 156, 43, 135, 212, 182, 106, 112, 219, 142, 151, 82, 56, 159, 247,
    106, 175, 32, 108, 237, 6, 58, 56, 249, 90, 237,
]);

/// Which window form this hop sends.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DammV2Form {
    /// The window without the optional group.
    Base,
    /// The window that carries it.
    RateLimited,
}

/// The accounts a MeteoraDammV2 hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MeteoraDammV2Accounts {
    /// Window slot 2.
    pub pool: Pubkey,
    /// The token account this hop spends from.
    pub input_token_account: Pubkey,
    /// The token account this hop receives into.
    pub output_token_account: Pubkey,
    /// Window slot 5.
    pub token_a_vault: Pubkey,
    /// Window slot 6.
    pub token_b_vault: Pubkey,
    /// Window slot 7.
    pub token_a_mint: Pubkey,
    /// Window slot 8.
    pub token_b_mint: Pubkey,
    /// The signer whose token accounts the swap moves through.
    pub payer: Pubkey,
    /// The program this venue reads at window slot 10.
    pub token_a_program: Pubkey,
    /// The program this venue reads at window slot 11.
    pub token_b_program: Pubkey,
    /// Window slot 12. Unset sends the venue's own program id, which the venue reads as no value.
    pub referral_token_account: Option<Pubkey>,
}

/// The window a MeteoraDammV2 hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: MeteoraDammV2Accounts, form: DammV2Form) -> VenueWindow {
    let mut metas = vec![
        readonly(PROGRAM_ID),
        readonly(POOL_AUTHORITY),
        writable(accounts.pool),
        writable(accounts.input_token_account),
        writable(accounts.output_token_account),
        writable(accounts.token_a_vault),
        writable(accounts.token_b_vault),
        readonly(accounts.token_a_mint),
        readonly(accounts.token_b_mint),
        signer(accounts.payer),
        readonly(accounts.token_a_program),
        readonly(accounts.token_b_program),
        accounts
            .referral_token_account
            .map_or_else(|| readonly(PROGRAM_ID), writable),
        readonly(EVENT_AUTHORITY),
        readonly(PROGRAM_ID),
    ];
    if matches!(form, DammV2Form::RateLimited) {
        metas.push(readonly(crate::programs::INSTRUCTIONS_SYSVAR_ID));
    }
    let account_count = u8::try_from(15usize.saturating_add(
        if matches!(form, DammV2Form::RateLimited) {
            1
        } else {
            0
        },
    ))
    .unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::MeteoraDammV2, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> MeteoraDammV2Accounts {
        MeteoraDammV2Accounts {
            pool: key(1),
            input_token_account: key(2),
            output_token_account: key(3),
            token_a_vault: key(4),
            token_b_vault: key(5),
            token_a_mint: key(6),
            token_b_mint: key(7),
            payer: key(8),
            token_a_program: key(9),
            token_b_program: key(10),
            referral_token_account: None,
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            EVENT_AUTHORITY.to_string(),
            "3rmHSu74h1ZcmAisVcWerTCiRDQbUrBKmcwptYGjHfet"
        );
        assert_eq!(
            POOL_AUTHORITY.to_string(),
            "HLnpSz9h2S4hiLQ43rnSD9XkcUThA7B8hQMKmDaiTLcC"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"
        );
    }

    #[test]
    fn the_shortest_window_is_15_accounts() {
        let window = resolve(sample(), DammV2Form::Base);
        assert_eq!(window.account_count(), 15);
        assert_eq!(window.account_metas().len(), 15);
        assert_eq!(window.hop_kind(), HopKind::MeteoraDammV2);
    }
}
