//! MeteoraDlmmSwap2.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo`
//! 1. `pool` — writable
//! 2. `bin_array_bitmap_extension` — writable
//! 3. `reserve_x` — writable
//! 4. `reserve_y` — writable
//! 5. `user_token_in` — writable
//! 6. `user_token_out` — writable
//! 7. `token_x_mint` — readonly
//! 8. `token_y_mint` — readonly
//! 9. `oracle` — writable
//! 10. `host_fee_in` — writable
//! 11. `user` — signer
//! 12. `token_x_program` — readonly
//! 13. `token_y_program` — readonly
//! 14. `memo_program` — readonly, pinned `MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr`
//! 15. `event_authority` — readonly, pinned `D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6`
//! 16. `program_self` — readonly, pinned `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo`
//! 17. `bin_array` — writable
//!
//! Then 1..=8 `BinArrayTail`, writable, appended in order.

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6`
pub const EVENT_AUTHORITY: Pubkey = Pubkey::new_from_array([
    178, 112, 214, 127, 169, 140, 81, 207, 2, 19, 5, 19, 88, 150, 43, 175, 53, 116, 43, 237, 89,
    201, 217, 68, 94, 156, 13, 12, 133, 199, 205, 145,
]);

/// `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    4, 233, 225, 47, 188, 132, 232, 38, 201, 50, 204, 233, 226, 100, 12, 206, 21, 89, 12, 28, 98,
    115, 176, 146, 87, 8, 186, 59, 133, 32, 176, 188,
]);

/// The tail's longest reach.
pub const MAX_BIN_ARRAYS: usize = 8;
/// This venue's variable tail, bounded at construction.
pub type BinArrayTail = super::PubkeyTail<MAX_BIN_ARRAYS>;

/// The accounts a MeteoraDlmmSwap2 hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MeteoraDlmmSwap2Accounts {
    /// Window slot 1.
    pub pool: Pubkey,
    /// Window slot 2. Unset sends the venue's own program id, which the venue reads as no value.
    pub bin_array_bitmap_extension: Option<Pubkey>,
    /// Window slot 3.
    pub reserve_x: Pubkey,
    /// Window slot 4.
    pub reserve_y: Pubkey,
    /// The token account this hop spends from.
    pub user_token_in: Pubkey,
    /// The token account this hop receives into.
    pub user_token_out: Pubkey,
    /// Window slot 7.
    pub token_x_mint: Pubkey,
    /// Window slot 8.
    pub token_y_mint: Pubkey,
    /// Window slot 9.
    pub oracle: Pubkey,
    /// Window slot 10. Unset sends the venue's own program id, which the venue reads as no value.
    pub host_fee_in: Option<Pubkey>,
    /// The signer whose token accounts the swap moves through.
    pub user: Pubkey,
    /// The program this venue reads at window slot 12.
    pub token_x_program: Pubkey,
    /// The program this venue reads at window slot 13.
    pub token_y_program: Pubkey,
}

/// The window a MeteoraDlmmSwap2 hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: MeteoraDlmmSwap2Accounts, tail: BinArrayTail) -> VenueWindow {
    let mut metas = vec![
        readonly(PROGRAM_ID),
        writable(accounts.pool),
        accounts
            .bin_array_bitmap_extension
            .map_or_else(|| readonly(PROGRAM_ID), writable),
        writable(accounts.reserve_x),
        writable(accounts.reserve_y),
        writable(accounts.user_token_in),
        writable(accounts.user_token_out),
        readonly(accounts.token_x_mint),
        readonly(accounts.token_y_mint),
        writable(accounts.oracle),
        accounts
            .host_fee_in
            .map_or_else(|| readonly(PROGRAM_ID), writable),
        signer(accounts.user),
        readonly(accounts.token_x_program),
        readonly(accounts.token_y_program),
        readonly(crate::programs::MEMO_PROGRAM_ID),
        readonly(EVENT_AUTHORITY),
        readonly(PROGRAM_ID),
    ];
    for key in tail.keys() {
        metas.push(writable(*key));
    }
    let account_count = u8::try_from(17usize.saturating_add(tail.len())).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::MeteoraDlmmSwap2, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> MeteoraDlmmSwap2Accounts {
        MeteoraDlmmSwap2Accounts {
            pool: key(1),
            bin_array_bitmap_extension: None,
            reserve_x: key(3),
            reserve_y: key(4),
            user_token_in: key(5),
            user_token_out: key(6),
            token_x_mint: key(7),
            token_y_mint: key(8),
            oracle: key(9),
            host_fee_in: None,
            user: key(11),
            token_x_program: key(12),
            token_y_program: key(13),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            EVENT_AUTHORITY.to_string(),
            "D1ZN9Wj1fRSUQfCjhvnu1hqDMT7hzjzBBpi12nVniYD6"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
        );
    }

    #[test]
    fn the_shortest_window_is_18_accounts() {
        let window = resolve(sample(), BinArrayTail::new(key(200)));
        assert_eq!(window.account_count(), 18);
        assert_eq!(window.account_metas().len(), 18);
        assert_eq!(window.hop_kind(), HopKind::MeteoraDlmmSwap2);
    }
}
