//! MeteoraDammV1.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB`
//! 1. `pool` — writable
//! 2. `user_source` — writable
//! 3. `user_dest` — writable
//! 4. `a_vault` — writable
//! 5. `b_vault` — writable
//! 6. `a_token_vault` — writable
//! 7. `b_token_vault` — writable
//! 8. `a_vault_lp_mint` — writable
//! 9. `b_vault_lp_mint` — writable
//! 10. `a_vault_lp` — writable
//! 11. `b_vault_lp` — writable
//! 12. `protocol_token_fee` — writable
//! 13. `payer` — signer
//! 14. `dynamic_vault_program` — readonly, pinned `24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi`
//! 15. `token_program` — readonly, pinned `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi`
pub const DYNAMIC_VAULT_PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    15, 191, 232, 132, 109, 104, 92, 189, 198, 44, 202, 126, 4, 199, 232, 246, 141, 204, 49, 58,
    179, 18, 119, 226, 224, 17, 42, 46, 192, 224, 82, 229,
]);

/// `Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    204, 248, 2, 212, 204, 204, 132, 215, 251, 33, 181, 247, 59, 73, 216, 26, 22, 197, 180, 200,
    142, 227, 35, 148, 225, 201, 29, 53, 136, 204, 64, 128,
]);

/// The accounts a MeteoraDammV1 hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MeteoraDammV1Accounts {
    /// Window slot 1.
    pub pool: Pubkey,
    /// The token account this hop spends from.
    pub user_source: Pubkey,
    /// The token account this hop receives into.
    pub user_dest: Pubkey,
    /// Window slot 4.
    pub a_vault: Pubkey,
    /// Window slot 5.
    pub b_vault: Pubkey,
    /// Window slot 6.
    pub a_token_vault: Pubkey,
    /// Window slot 7.
    pub b_token_vault: Pubkey,
    /// Window slot 8.
    pub a_vault_lp_mint: Pubkey,
    /// Window slot 9.
    pub b_vault_lp_mint: Pubkey,
    /// Window slot 10.
    pub a_vault_lp: Pubkey,
    /// Window slot 11.
    pub b_vault_lp: Pubkey,
    /// Window slot 12.
    pub protocol_token_fee: Pubkey,
    /// The signer whose token accounts the swap moves through.
    pub payer: Pubkey,
}

/// The window a MeteoraDammV1 hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: MeteoraDammV1Accounts) -> VenueWindow {
    let metas = vec![
        readonly(PROGRAM_ID),
        writable(accounts.pool),
        writable(accounts.user_source),
        writable(accounts.user_dest),
        writable(accounts.a_vault),
        writable(accounts.b_vault),
        writable(accounts.a_token_vault),
        writable(accounts.b_token_vault),
        writable(accounts.a_vault_lp_mint),
        writable(accounts.b_vault_lp_mint),
        writable(accounts.a_vault_lp),
        writable(accounts.b_vault_lp),
        writable(accounts.protocol_token_fee),
        signer(accounts.payer),
        readonly(DYNAMIC_VAULT_PROGRAM_ID),
        readonly(crate::programs::TOKEN_PROGRAM_ID),
    ];
    let account_count = u8::try_from(16).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::MeteoraDammV1, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> MeteoraDammV1Accounts {
        MeteoraDammV1Accounts {
            pool: key(1),
            user_source: key(2),
            user_dest: key(3),
            a_vault: key(4),
            b_vault: key(5),
            a_token_vault: key(6),
            b_token_vault: key(7),
            a_vault_lp_mint: key(8),
            b_vault_lp_mint: key(9),
            a_vault_lp: key(10),
            b_vault_lp: key(11),
            protocol_token_fee: key(12),
            payer: key(13),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            DYNAMIC_VAULT_PROGRAM_ID.to_string(),
            "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
        );
    }

    #[test]
    fn the_shortest_window_is_16_accounts() {
        let window = resolve(sample());
        assert_eq!(window.account_count(), 16);
        assert_eq!(window.account_metas().len(), 16);
        assert_eq!(window.hop_kind(), HopKind::MeteoraDammV1);
    }
}
