//! PumpSwapBuy.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA`
//! 1. `pool` — writable
//! 2. `user` — writable, signer
//! 3. `forwarded_before_base_mint` — readonly
//! 4. `base_mint` — readonly
//! 5. `quote_mint` — readonly
//! 6. `base_token_account` — writable
//! 7. `quote_token_account` — writable
//! 8. `base_vault` — writable
//! 9. `quote_vault` — writable
//! 10. `forwarded_before_volume_accumulator` — readonly
//! 11. `forwarded_before_volume_accumulator` — writable
//! 12. `forwarded_before_volume_accumulator` — readonly
//! 13. `forwarded_before_volume_accumulator` — readonly
//! 14. `forwarded_before_volume_accumulator` — readonly
//! 15. `forwarded_before_volume_accumulator` — readonly
//! 16. `forwarded_before_volume_accumulator` — readonly
//! 17. `forwarded_before_volume_accumulator` — readonly
//! 18. `forwarded_before_volume_accumulator` — writable
//! 19. `forwarded_before_volume_accumulator` — readonly
//! 20. `global_volume_accumulator` — readonly, pinned `C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw`
//! 21. `user_volume_accumulator` — writable
//! 22. `fee_config` — readonly, pinned `5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx`
//! 23. `fee_program` — readonly, pinned `pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ`
//! 24. `forwarded_close` — readonly
//! 25. `forwarded_close` — writable

use solana_instruction::AccountMeta;
use solana_pubkey::Pubkey;

use super::{readonly, writable, VenueWindow};
use crate::HopKind;

/// `5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx`
pub const FEE_CONFIG: Pubkey = Pubkey::new_from_array([
    65, 36, 110, 204, 125, 120, 254, 129, 228, 23, 115, 164, 105, 101, 65, 153, 55, 146, 58, 7,
    100, 71, 151, 223, 111, 62, 181, 20, 66, 96, 16, 203,
]);

/// `pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ`
pub const FEE_PROGRAM: Pubkey = Pubkey::new_from_array([
    12, 53, 255, 169, 5, 90, 142, 86, 141, 168, 247, 188, 7, 86, 21, 39, 76, 241, 201, 44, 164, 31,
    64, 0, 156, 81, 106, 164, 20, 194, 124, 112,
]);

/// `C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw`
pub const GLOBAL_VOLUME_ACCUMULATOR: Pubkey = Pubkey::new_from_array([
    163, 215, 187, 18, 126, 88, 173, 193, 44, 166, 143, 131, 67, 126, 194, 225, 195, 249, 130, 13,
    233, 62, 88, 249, 23, 138, 41, 24, 221, 170, 247, 180,
]);

/// `pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86,
    213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99,
]);

/// The accounts a PumpSwapBuy hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PumpSwapBuyAccounts {
    /// Window slot 1.
    pub pool: Pubkey,
    /// The signer whose token accounts the swap moves through.
    pub user: Pubkey,
    /// Window slot 3, forwarded to the venue without validation.
    pub forwarded_before_base_mint: Pubkey,
    /// Window slot 4.
    pub base_mint: Pubkey,
    /// Window slot 5.
    pub quote_mint: Pubkey,
    /// One of the trader's two token accounts; the leg decides which one is spent.
    pub base_token_account: Pubkey,
    /// One of the trader's two token accounts; the leg decides which one is spent.
    pub quote_token_account: Pubkey,
    /// Window slot 8.
    pub base_vault: Pubkey,
    /// Window slot 9.
    pub quote_vault: Pubkey,
    /// Window slots 10..=19, forwarded to the venue without validation.
    pub forwarded_before_volume_accumulator: [Pubkey; 10],
    /// Window slot 21.
    pub user_volume_accumulator: Pubkey,
    /// Optional; supplying it appends 1 account(s) at window slot 24.
    pub cashback: Option<Pubkey>,
    /// Optional; supplying it appends 1 account(s) at window slot 24.
    pub pool_v2: Option<Pubkey>,
    /// Window slots 24..=25, forwarded to the venue without validation.
    pub forwarded_close: [Pubkey; 2],
}

/// The window a PumpSwapBuy hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: PumpSwapBuyAccounts) -> VenueWindow {
    let mut metas = vec![
        readonly(PROGRAM_ID),
        writable(accounts.pool),
        AccountMeta::new(accounts.user, true),
        readonly(accounts.forwarded_before_base_mint),
        readonly(accounts.base_mint),
        readonly(accounts.quote_mint),
        writable(accounts.base_token_account),
        writable(accounts.quote_token_account),
        writable(accounts.base_vault),
        writable(accounts.quote_vault),
        readonly(accounts.forwarded_before_volume_accumulator[0]),
        writable(accounts.forwarded_before_volume_accumulator[1]),
        readonly(accounts.forwarded_before_volume_accumulator[2]),
        readonly(accounts.forwarded_before_volume_accumulator[3]),
        readonly(accounts.forwarded_before_volume_accumulator[4]),
        readonly(accounts.forwarded_before_volume_accumulator[5]),
        readonly(accounts.forwarded_before_volume_accumulator[6]),
        readonly(accounts.forwarded_before_volume_accumulator[7]),
        writable(accounts.forwarded_before_volume_accumulator[8]),
        readonly(accounts.forwarded_before_volume_accumulator[9]),
        readonly(GLOBAL_VOLUME_ACCUMULATOR),
        writable(accounts.user_volume_accumulator),
        readonly(FEE_CONFIG),
        readonly(FEE_PROGRAM),
    ];
    if let Some(key) = accounts.cashback {
        metas.push(writable(key));
    }
    if let Some(key) = accounts.pool_v2 {
        metas.push(readonly(key));
    }
    metas.push(readonly(accounts.forwarded_close[0]));
    metas.push(writable(accounts.forwarded_close[1]));
    let account_count = u8::try_from(
        26usize
            .saturating_add(if accounts.cashback.is_some() { 1 } else { 0 })
            .saturating_add(if accounts.pool_v2.is_some() { 1 } else { 0 }),
    )
    .unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::PumpSwapBuy, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> PumpSwapBuyAccounts {
        PumpSwapBuyAccounts {
            pool: key(1),
            user: key(2),
            forwarded_before_base_mint: key(3),
            base_mint: key(4),
            quote_mint: key(5),
            base_token_account: key(6),
            quote_token_account: key(7),
            base_vault: key(8),
            quote_vault: key(9),
            forwarded_before_volume_accumulator: [
                key(10),
                key(11),
                key(12),
                key(13),
                key(14),
                key(15),
                key(16),
                key(17),
                key(18),
                key(19),
            ],
            user_volume_accumulator: key(11),
            cashback: None,
            pool_v2: None,
            forwarded_close: [key(14), key(15)],
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            FEE_CONFIG.to_string(),
            "5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx"
        );
        assert_eq!(
            FEE_PROGRAM.to_string(),
            "pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"
        );
        assert_eq!(
            GLOBAL_VOLUME_ACCUMULATOR.to_string(),
            "C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
        );
    }

    #[test]
    fn the_shortest_window_is_26_accounts() {
        let window = resolve(sample());
        assert_eq!(window.account_count(), 26);
        assert_eq!(window.account_metas().len(), 26);
        assert_eq!(window.hop_kind(), HopKind::PumpSwapBuy);
    }
}
