//! RaydiumClmm.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK`
//! 1. `payer` — signer
//! 2. `amm_config` — readonly
//! 3. `pool` — writable
//! 4. `input_token_account` — writable
//! 5. `output_token_account` — writable
//! 6. `input_vault` — writable
//! 7. `output_vault` — writable
//! 8. `observation_state` — writable
//! 9. `token_program` — readonly, pinned `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`
//! 10. `token_2022_program` — readonly, pinned `TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`
//! 11. `memo_program` — readonly, pinned `MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr`
//! 12. `input_mint` — readonly
//! 13. `output_mint` — readonly
//! 14. `tick_array` — writable
//!
//! Then 1..=7 `ClmmTail`, writable, appended in order.

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    165, 213, 202, 158, 4, 207, 93, 181, 144, 183, 20, 186, 47, 227, 44, 177, 89, 19, 63, 193, 193,
    146, 183, 34, 87, 253, 7, 211, 156, 176, 64, 30,
]);

/// The tail's longest reach.
pub const TAIL_MAX: usize = 7;
/// This venue's variable tail, bounded at construction.
pub type ClmmTail = super::PubkeyTail<TAIL_MAX>;

/// The accounts a RaydiumClmm hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaydiumClmmAccounts {
    /// The signer whose token accounts the swap moves through.
    pub payer: Pubkey,
    /// Window slot 2.
    pub amm_config: Pubkey,
    /// Window slot 3.
    pub pool: Pubkey,
    /// The token account this hop spends from.
    pub input_token_account: Pubkey,
    /// The token account this hop receives into.
    pub output_token_account: Pubkey,
    /// Window slot 6.
    pub input_vault: Pubkey,
    /// Window slot 7.
    pub output_vault: Pubkey,
    /// Window slot 8.
    pub observation_state: Pubkey,
    /// Window slot 12.
    pub input_mint: Pubkey,
    /// Window slot 13.
    pub output_mint: Pubkey,
}

/// The window a RaydiumClmm hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: RaydiumClmmAccounts, tail: ClmmTail) -> VenueWindow {
    let mut metas = vec![
        readonly(PROGRAM_ID),
        signer(accounts.payer),
        readonly(accounts.amm_config),
        writable(accounts.pool),
        writable(accounts.input_token_account),
        writable(accounts.output_token_account),
        writable(accounts.input_vault),
        writable(accounts.output_vault),
        writable(accounts.observation_state),
        readonly(crate::programs::TOKEN_PROGRAM_ID),
        readonly(crate::programs::TOKEN_2022_PROGRAM_ID),
        readonly(crate::programs::MEMO_PROGRAM_ID),
        readonly(accounts.input_mint),
        readonly(accounts.output_mint),
    ];
    for key in tail.keys() {
        metas.push(writable(*key));
    }
    let account_count = u8::try_from(14usize.saturating_add(tail.len())).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::RaydiumClmm, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> RaydiumClmmAccounts {
        RaydiumClmmAccounts {
            payer: key(1),
            amm_config: key(2),
            pool: key(3),
            input_token_account: key(4),
            output_token_account: key(5),
            input_vault: key(6),
            output_vault: key(7),
            observation_state: key(8),
            input_mint: key(9),
            output_mint: key(10),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            PROGRAM_ID.to_string(),
            "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"
        );
    }

    #[test]
    fn the_shortest_window_is_15_accounts() {
        let window = resolve(sample(), ClmmTail::new(key(200)));
        assert_eq!(window.account_count(), 15);
        assert_eq!(window.account_metas().len(), 15);
        assert_eq!(window.hop_kind(), HopKind::RaydiumClmm);
    }
}
