//! RaydiumCpmm.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C`
//! 1. `user` — signer
//! 2. `authority` — readonly, pinned `GpMZbSM2GgvTKHJirzeGfMFoaZ8UR2X7F4v8vHTvxFbL`
//! 3. `amm_config` — readonly
//! 4. `pool` — writable
//! 5. `input_token_account` — writable
//! 6. `output_token_account` — writable
//! 7. `input_vault` — writable
//! 8. `output_vault` — writable
//! 9. `input_token_program` — readonly
//! 10. `output_token_program` — readonly
//! 11. `input_mint` — readonly
//! 12. `output_mint` — readonly
//! 13. `observation_state` — writable

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `GpMZbSM2GgvTKHJirzeGfMFoaZ8UR2X7F4v8vHTvxFbL`
pub const AUTHORITY: Pubkey = Pubkey::new_from_array([
    235, 0, 217, 245, 178, 146, 180, 33, 74, 199, 208, 55, 180, 214, 240, 100, 80, 185, 100, 96,
    13, 243, 115, 5, 43, 181, 232, 79, 47, 142, 154, 103,
]);

/// `CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    169, 42, 90, 139, 79, 41, 89, 82, 132, 37, 80, 170, 147, 253, 91, 149, 181, 172, 230, 168, 235,
    146, 12, 147, 148, 46, 67, 105, 12, 32, 236, 115,
]);

/// The accounts a RaydiumCpmm hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaydiumCpmmAccounts {
    /// The signer whose token accounts the swap moves through.
    pub user: Pubkey,
    /// Window slot 3.
    pub amm_config: Pubkey,
    /// Window slot 4.
    pub pool: Pubkey,
    /// The token account this hop spends from.
    pub input_token_account: Pubkey,
    /// The token account this hop receives into.
    pub output_token_account: Pubkey,
    /// Window slot 7.
    pub input_vault: Pubkey,
    /// Window slot 8.
    pub output_vault: Pubkey,
    /// The program this venue reads at window slot 9.
    pub input_token_program: Pubkey,
    /// The program this venue reads at window slot 10.
    pub output_token_program: Pubkey,
    /// Window slot 11.
    pub input_mint: Pubkey,
    /// Window slot 12.
    pub output_mint: Pubkey,
    /// Window slot 13.
    pub observation_state: Pubkey,
}

/// The window a RaydiumCpmm hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: RaydiumCpmmAccounts) -> VenueWindow {
    let metas = vec![
        readonly(PROGRAM_ID),
        signer(accounts.user),
        readonly(AUTHORITY),
        readonly(accounts.amm_config),
        writable(accounts.pool),
        writable(accounts.input_token_account),
        writable(accounts.output_token_account),
        writable(accounts.input_vault),
        writable(accounts.output_vault),
        readonly(accounts.input_token_program),
        readonly(accounts.output_token_program),
        readonly(accounts.input_mint),
        readonly(accounts.output_mint),
        writable(accounts.observation_state),
    ];
    let account_count = u8::try_from(14).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::RaydiumCpmm, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> RaydiumCpmmAccounts {
        RaydiumCpmmAccounts {
            user: key(1),
            amm_config: key(2),
            pool: key(3),
            input_token_account: key(4),
            output_token_account: key(5),
            input_vault: key(6),
            output_vault: key(7),
            input_token_program: key(8),
            output_token_program: key(9),
            input_mint: key(10),
            output_mint: key(11),
            observation_state: key(12),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            AUTHORITY.to_string(),
            "GpMZbSM2GgvTKHJirzeGfMFoaZ8UR2X7F4v8vHTvxFbL"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"
        );
    }

    #[test]
    fn the_shortest_window_is_14_accounts() {
        let window = resolve(sample());
        assert_eq!(window.account_count(), 14);
        assert_eq!(window.account_metas().len(), 14);
        assert_eq!(window.hop_kind(), HopKind::RaydiumCpmm);
    }
}
