//! RaydiumAmmV4.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8`
//! 1. `token_program` — readonly, pinned `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`
//! 2. `pool` — writable
//! 3. `amm_authority` — readonly, pinned `5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1`
//! 4. `base_vault` — writable
//! 5. `quote_vault` — writable
//! 6. `user_source` — writable
//! 7. `user_destination` — writable
//! 8. `payer` — signer

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1`
pub const AMM_AUTHORITY: Pubkey = Pubkey::new_from_array([
    65, 87, 176, 88, 15, 49, 197, 252, 228, 74, 98, 88, 45, 188, 249, 215, 142, 231, 89, 67, 160,
    132, 163, 147, 179, 80, 54, 141, 34, 137, 147, 8,
]);

/// `675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    75, 217, 73, 196, 54, 2, 195, 63, 32, 119, 144, 237, 22, 163, 82, 76, 161, 185, 151, 92, 241,
    33, 162, 169, 12, 255, 236, 125, 248, 182, 138, 205,
]);

/// The accounts a RaydiumAmmV4 hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RaydiumAmmV4Accounts {
    /// Window slot 2.
    pub pool: Pubkey,
    /// Window slot 4.
    pub base_vault: Pubkey,
    /// Window slot 5.
    pub quote_vault: Pubkey,
    /// The token account this hop spends from.
    pub user_source: Pubkey,
    /// The token account this hop receives into.
    pub user_destination: Pubkey,
    /// The signer whose token accounts the swap moves through.
    pub payer: Pubkey,
}

/// The window a RaydiumAmmV4 hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: RaydiumAmmV4Accounts) -> VenueWindow {
    let metas = vec![
        readonly(PROGRAM_ID),
        readonly(crate::programs::TOKEN_PROGRAM_ID),
        writable(accounts.pool),
        readonly(AMM_AUTHORITY),
        writable(accounts.base_vault),
        writable(accounts.quote_vault),
        writable(accounts.user_source),
        writable(accounts.user_destination),
        signer(accounts.payer),
    ];
    let account_count = u8::try_from(9).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::RaydiumAmmV4, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> RaydiumAmmV4Accounts {
        RaydiumAmmV4Accounts {
            pool: key(1),
            base_vault: key(2),
            quote_vault: key(3),
            user_source: key(4),
            user_destination: key(5),
            payer: key(6),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            AMM_AUTHORITY.to_string(),
            "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"
        );
        assert_eq!(
            PROGRAM_ID.to_string(),
            "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
        );
    }

    #[test]
    fn the_shortest_window_is_9_accounts() {
        let window = resolve(sample());
        assert_eq!(window.account_count(), 9);
        assert_eq!(window.account_metas().len(), 9);
        assert_eq!(window.hop_kind(), HopKind::RaydiumAmmV4);
    }
}
