//! Whirlpool.
//!
//! Generated by `wire-export` from the router's window schema. Do not edit: a change
//! here is a change to the deployed program's window contract, which lives there.
//!
//! # Slots
//!
//! 0. `program` — readonly, pinned `whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc`
//! 1. `token_program_a` — readonly
//! 2. `token_program_b` — readonly
//! 3. `memo_program` — readonly, pinned `MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr`
//! 4. `token_authority` — signer
//! 5. `whirlpool` — writable
//! 6. `mint_a` — readonly
//! 7. `mint_b` — readonly
//! 8. `token_owner_account_a` — writable
//! 9. `token_vault_a` — writable
//! 10. `token_owner_account_b` — writable
//! 11. `token_vault_b` — writable
//! 12. `tick_array_0` — writable
//! 13. `tick_array_1` — writable
//! 14. `tick_array_2` — writable
//! 15. `oracle` — writable
//!
//! Then 0..=3 `SupplementalTickArrays`, writable, appended in order.

use solana_pubkey::Pubkey;

use super::{readonly, signer, writable, VenueWindow};
use crate::HopKind;

/// `whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc`
pub const PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    14, 3, 104, 95, 142, 144, 144, 83, 228, 88, 18, 28, 102, 245, 167, 106, 237, 199, 112, 106,
    161, 28, 130, 248, 170, 149, 42, 143, 43, 120, 121, 169,
]);

/// Zero to 3 accounts, appended in order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SupplementalTickArrays {
    len: u8,
    keys: [Pubkey; 3],
}

impl SupplementalTickArrays {
    /// How many accounts the tail holds, `0..=3`.
    #[must_use]
    pub const fn len(&self) -> u8 {
        self.len
    }

    /// Whether the tail is empty.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// The accounts, in order.
    #[must_use]
    pub fn keys(&self) -> &[Pubkey] {
        self.keys.get(..usize::from(self.len)).unwrap_or(&[])
    }
}

impl From<[Pubkey; 0]> for SupplementalTickArrays {
    fn from(_: [Pubkey; 0]) -> Self {
        Self {
            len: 0,
            keys: [Pubkey::default(), Pubkey::default(), Pubkey::default()],
        }
    }
}

impl From<[Pubkey; 1]> for SupplementalTickArrays {
    fn from(keys: [Pubkey; 1]) -> Self {
        let [key_0] = keys;
        Self {
            len: 1,
            keys: [key_0, Pubkey::default(), Pubkey::default()],
        }
    }
}

impl From<[Pubkey; 2]> for SupplementalTickArrays {
    fn from(keys: [Pubkey; 2]) -> Self {
        let [key_0, key_1] = keys;
        Self {
            len: 2,
            keys: [key_0, key_1, Pubkey::default()],
        }
    }
}

impl From<[Pubkey; 3]> for SupplementalTickArrays {
    fn from(keys: [Pubkey; 3]) -> Self {
        let [key_0, key_1, key_2] = keys;
        Self {
            len: 3,
            keys: [key_0, key_1, key_2],
        }
    }
}

/// The accounts a Whirlpool hop takes, named in window order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WhirlpoolAccounts {
    /// The program this venue reads at window slot 1.
    pub token_program_a: Pubkey,
    /// The program this venue reads at window slot 2.
    pub token_program_b: Pubkey,
    /// The signer whose token accounts the swap moves through.
    pub token_authority: Pubkey,
    /// Window slot 5.
    pub whirlpool: Pubkey,
    /// Window slot 6.
    pub mint_a: Pubkey,
    /// Window slot 7.
    pub mint_b: Pubkey,
    /// One of the trader's two token accounts; the leg decides which one is spent.
    pub token_owner_account_a: Pubkey,
    /// Window slot 9.
    pub token_vault_a: Pubkey,
    /// One of the trader's two token accounts; the leg decides which one is spent.
    pub token_owner_account_b: Pubkey,
    /// Window slot 11.
    pub token_vault_b: Pubkey,
    /// Window slot 12.
    pub tick_array_0: Pubkey,
    /// Window slot 13.
    pub tick_array_1: Pubkey,
    /// Window slot 14.
    pub tick_array_2: Pubkey,
    /// Window slot 15.
    pub oracle: Pubkey,
}

/// The window a Whirlpool hop sends, slot for slot.
#[must_use]
pub fn resolve(accounts: &WhirlpoolAccounts, tail: SupplementalTickArrays) -> VenueWindow {
    let mut metas = vec![
        readonly(PROGRAM_ID),
        readonly(accounts.token_program_a),
        readonly(accounts.token_program_b),
        readonly(crate::programs::MEMO_PROGRAM_ID),
        signer(accounts.token_authority),
        writable(accounts.whirlpool),
        readonly(accounts.mint_a),
        readonly(accounts.mint_b),
        writable(accounts.token_owner_account_a),
        writable(accounts.token_vault_a),
        writable(accounts.token_owner_account_b),
        writable(accounts.token_vault_b),
        writable(accounts.tick_array_0),
        writable(accounts.tick_array_1),
        writable(accounts.tick_array_2),
        writable(accounts.oracle),
    ];
    for key in tail.keys() {
        metas.push(writable(*key));
    }
    let account_count =
        u8::try_from(16usize.saturating_add(usize::from(tail.len()))).unwrap_or(u8::MAX);
    VenueWindow::new(HopKind::Whirlpool, account_count, metas)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(byte: u8) -> Pubkey {
        Pubkey::new_from_array([byte; 32])
    }

    fn sample() -> WhirlpoolAccounts {
        WhirlpoolAccounts {
            token_program_a: key(1),
            token_program_b: key(2),
            token_authority: key(3),
            whirlpool: key(4),
            mint_a: key(5),
            mint_b: key(6),
            token_owner_account_a: key(7),
            token_vault_a: key(8),
            token_owner_account_b: key(9),
            token_vault_b: key(10),
            tick_array_0: key(11),
            tick_array_1: key(12),
            tick_array_2: key(13),
            oracle: key(14),
        }
    }

    #[test]
    fn the_pinned_addresses_are_the_documented_ones() {
        assert_eq!(
            PROGRAM_ID.to_string(),
            "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
        );
    }

    #[test]
    fn the_shortest_window_is_16_accounts() {
        let window = resolve(&sample(), SupplementalTickArrays::from([]));
        assert_eq!(window.account_count(), 16);
        assert_eq!(window.account_metas().len(), 16);
        assert_eq!(window.hop_kind(), HopKind::Whirlpool);
    }
}
